<?php
/**
 * View Name: form
 * Path: view/form
 * 
 * @param array $data argumets passed from controller
 * 
 */
?>
{{ title:: "Validation Error testing" }}
{{ keywords:: "meta keywords here" }}
{{ description:: "meta description here" }}
{{ bodyClass:: "body classes here" }}

{{ content }}
  
  <?php
  dump( errors() ) 
  ?>
  <?php if (has_error('email')) : ?>
    <h4><?=get_error('email')?></h4>
  <?php endif; ?>

  <?php if (has_error('pass')) : ?>
    <h4><?=get_error('pass')?></h4>
  <?php endif; ?>

  <form action="" method="post">
    <?=CSRF_FIELD?>
    <input type="text" name="name" placeholder="Name">
    <input type="email" name="email" placeholder="Email Address">
    <input type="submit" value="Submit">
  </form>
{{ content-end }}
