<?php    
    $user['names'] = ['fname' => 'John', 'lname' => 'Doe', 'Mariya'];
    $user['ages'] = [26, 30, 28];    
?>

{{ title:: data.0 }}

{{ content }}
<div class="container">
    <!-- {: c-user | user.ages :}
    {: c-user | user.names :} -->

    <?php dump( errors() ); ?>

    <?php if (has_error('username')) : ?>
        <h3><?=get_error('username')?></h3>
    <?php endif; ?>
</div>
{{ content-end }}

{{ customJS }}
<script nonce="<?=CSP_NONCE?>"> let data = <?= $data_json ?>; </script>
{{ customJS-end }}