<?php
/**
 * View Name: http-error
 * Path: view/http-error
 * 
 * @param array $data arguments passed from ozz core or app/functions.php
 */
?>

{{ title      = '<?=$error_message?>' }}
{{ body_class = 'light-bg' }}

{{ content }}
  <section class="error-component">
    <div class="container center">
      <h1><?=$error_code?></h1>
      <h2><?=$error_message?></h2>
    </div>
  </section>
{{ content-end }}