<?php
/**
 * View Name: http-error
 * Path: view/http-error
 * @param array $data arguments passed from ozz core or app/functions.php
 */
?>

{{ title = '<?=$error_message?>' }}
{{ body_class = 'error-page' }}

{{ content }}
<section class="app-view app-view--error">
  <div class="app-container">
    <h1 class="app-error__code"><?=$error_code?></h1>
    <p class="app-error__message"><?=$error_message?></p>
  </div>
</section>
{{ content-end }}
