{{ title:: "Welcome to <?=APP_NAME?>" }}
{{ keywords:: "test" }}
{{ description:: "title.name" }}
{{ bodyClass:: "body classes here" }}

{{ content }}
<div class="container">
    <div class="greeting">
        <div class="inner">
            <h1><?=$data['greeting']?></h1>
            <h4>A Simplest and Light-weight micro framework for PHP</h4>
            <div>
                <a href="#"><button>Documentation</button></a>
            </div>
        </div>
    </div>
</div>
{{ content-end }}
