{{ title        = "Welcome to <?=APP_NAME?>" }}
{{ keywords     = "meta_keywords" }}
{{ description  = "meta_description" }}
{{ body_class   = "view-welcome" }}

{{ content }}
<section class="welcome">
  <div class="container">
    <div class="inner">
      <h1><?=$greeting?></h1>
      <h4><?=$caption?></h4>
      <a href="<?=$button['link']?>" class="button">
        <?=$button['text']?>
      </a>
    </div>
  </div>
</section>
{{ content-end }}