{{ title        = "Welcome to <?=APP_NAME?>" }}
{{ keywords     = "meta_keywords" }}
{{ description  = "meta_description" }}
{{ body_class   = "view-welcome" }}

{{ content }}
<section class="welcome">
  <div class="container">
    <div class="inner">
      <h1><?=$data['greeting']?></h1>
      <h4><?=$data['caption']?></h4>
      <a href="<?=$data['button']['link']?>" class="button">
        <?=$data['button']['text']?>
      </a>
    </div>
  </div>
</section>
{{ content-end }}