<section>
	<div class="container">
		<?php dump($data) ?>
		<h1>User: <span style="color:#88bf3d"></?= //$data[0]['email'] ?></span></h1>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt minima odio eveniet inventore veritatis quo natus aspernatur nobis, nulla, tenetur est nisi facilis. Totam ad saepe laudantium voluptatibus consequuntur
		sunt?</p>
		
		<?php if (isset($lname)) : ?>
		<h1><?=$fname.' '.$lname?></h1>
		<?php endif; ?>

		<?php dump($args); ?>
		
		<?php if($args) : ?>
			<ul>
				<?php foreach ($args as $value) : ?>
					<?php if (is_string($value)) :?>
						<li><?php echo $value; ?></li>
					<?php endif;?>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>

		<button>Login</button>
	</div>
</section>