<section>
    <?php if (isset($data['error'])) : ?>
        <li><?=$data['message']?></li>
    <?php endif; ?>

    <div class="container">
        <h1><?=$args['heading'] ?></h1>
        <form action="/file" method="post" enctype="multipart/form-data">
            <input type="file" name="fileToUpload" id="fileToUpload" />
            <input type="submit" value="Upload Image" name="submit">
        </form>
    </div>
</section>