<?php
/**
 * Component Name: header
 * Path: view/components/header
 * 
 * @param array $args Given arguments on component call
 * 
 */
?>

<header>
  <div class="container">
    <a href="<?=BASE_URL?>">
      <div class="logo">LOGO</div>
    </a>
    <nav>
      <ul>
        <?php if(is_logged_in()) : ?>
          <li><a href="/dashboard">Dashboard</a></li>
          <li><a href="/logout">Logout</a></li>
        <?php else: ?>
          <li><a href="/login">Login</a></li>
          <li><a href="/sign-up">Sign Up</a></li>
        <?php endif; ?>
      </ul>
    </nav>
  </div>
</header>