<?php
/**
 * Component Name: header
 * Path: view/components/header
 * @param array $args Given arguments on component call
 */
?>

<header class="app-header">
  <div class="app-container app-header__inner">
    <div class="app-header__brand">
      <a href="<?=BASE_URL?>">
        <img src="<?=ASSETS?>icons/logo.svg" alt="Logo">
      </a>
    </div>

    <nav class="app-header__nav">
      <?php if (is_logged_in()) : ?>
        <a href="/admin" class="app-nav__link">Admin</a>
        <a href="/logout" class="app-nav__link">Logout</a>
      <?php elseif (is_auth_created()) : ?>
        <a href="/login" class="app-nav__link">Login</a>
        <a href="/sign-up" class="app-nav__link">Sign Up</a>
      <?php endif; ?>
    </nav>
  </div>
</header>