<?php
/**
 * Component Name: header
 * Path: view/components/header
 * @param array $args Given arguments on component call
 */
?>

<header class="navbar is-fixed-top has-shadow">
  <div class="container">
    <div class="navbar-brand">
      <a href="<?=BASE_URL?>" class="navbar-item">
        <img src="<?=ASSETS?>icons/logo.svg" alt="Logo">
      </a>
    </div>

    <div class="navbar-menu is-active">
      <div class="navbar-end">
        <?php if (is_logged_in()) : ?>
          <a href="/admin" class="navbar-item">Admin</a>
          <a href="/logout" class="navbar-item">Logout</a>
        <?php elseif (is_auth_created()) : ?>
          <a href="/login" class="navbar-item">Login</a>
          <a href="/sign-up" class="navbar-item">Sign Up</a>
        <?php endif; ?>
      </div>
    </div>
  </div>
</header>