<!DOCTYPE html>
<html lang="<?=locale()?>" data-theme="light">
<head>
  <meta charset=<?=CONFIG['CHARSET']?>>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="keywords" content="{% keywords %}">
  <meta name="description" content="{% description %}">
  <meta name="csrf-token" content="<?=csrf_token()?>">
  <meta name="url" content="<?=base_url()?>">
  <link rel="icon" type="image/x-icon" href="<?=asset("assets/icons/favicon.svg")?>">
  <link nonce="<?=csp_nonce()?>" rel="stylesheet" href="<?=asset("assets/css/style.css")?>">
</head>
<body class="{% body_class %}">

  <?=component('header')?>

  <main>
    {% content %}
  </main>

  <?=component('footer')?>

<script nonce="<?=csp_nonce()?>" src="<?=asset("assets/js/app.js")?>"></script>
</body>
</html>