<!DOCTYPE html>
<html lang="<?=APP_LANG?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="keywords" content="{% keywords %}">
  <meta name="description" content="{% description %}">
  <meta name="csrf-token" content="<?=CSRF_TOKEN?>">
  <meta name="url" content="<?=BASE_URL?>">
  <link rel="icon" type="image/x-icon" href="<?=BASE_URL?>assets/icons/favicon.ico">
  <link rel="stylesheet" href="<?=CSS?>styles.css" nonce="<?=CSP_NONCE?>">
</head>
<body class="{% bodyClass %}">

  <?=component('header')?>

  <main>
    {% content %}
  </main>

  <?=component('footer')?>

<script nonce="<?=CSP_NONCE?>" src="<?=JS?>app.js"></script>
</body>
</html>
