<!DOCTYPE html>
<html lang="<?=APP_LANG?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="keywords" content="{% keywords %}">
  <meta name="description" content="{% description %}">
  <meta name="robots" content="index, follow">
  <meta name="csrf-token" content="<?=CSRF_TOKEN?>">
  <meta name="url" content="<?=BASE_URL?>">
  <meta name="copyright" content="<?=APP_NAME?>">
  <meta name="apple-mobile-web-app-capable" content="yes" >
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="#dddddd">
  <link rel="apple-touch-icon" sizes="180x180" href="<?=ASSETS?>icons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="<?=ASSETS?>icons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="<?=ASSETS?>icons/favicon-16x16.png">
  <link rel="mask-icon" href="<?=ASSETS?>icons/safari-pinned-tab.svg" color="#5bbad5">
  <link rel="stylesheet" href="<?=CSS?>styles.css" nonce="<?=CSP_NONCE?>">
</head>
<body class="{% bodyClass %}">

<main>
  {% content %}
</main>

<script nonce="<?=CSP_NONCE?>" src="<?=JS?>app.js"></script>
</body>
</html>
